name: 'Openrouter Code Reviewer Action'
description: 'Automated code review using Openrouter AI models for pull requests'
author: 'Kristiansnts'

branding:
  icon: 'eye'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openrouter-api-key:
    description: 'OpenRouter API key for accessing AI models'
    required: true
  file-pattern:
    description: 'Glob pattern for files to review (e.g., "**/*.{ts,tsx}")'
    required: false
    default: '**/*.{js,jsx,ts,tsx,py,php}'
  model:
    description: 'OpenRouter model to use for code review'
    required: false
    default: 'deepseek/deepseek-r1-distill-llama-70b:free'
  base-branch:
    description: 'Base branch to compare against'
    required: false
    default: ''
  concurrency-limit:
    description: 'Number of files to review concurrently'
    required: false
    default: '5'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      uses: tj-actions/changed-files@v42
      id: changed-files

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: npm install parse-diff minimatch glob

    - name: Run Code Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OPENROUTER_API_KEY: ${{ inputs.openrouter-api-key }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        FILE_PATTERN: ${{ inputs.file-pattern }}
        BASE_BRANCH: ${{ inputs.base-branch || github.event.pull_request.base.ref }}
        MODEL: ${{ inputs.model }}
        CONCURRENCY_LIMIT: ${{ inputs.concurrency-limit }}
      run: node ${{ github.action_path }}/scripts/code-review/main.js
