name: Openrouter Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.py'  # Adjust for your code language
      - '**/*.php'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '!**/*.yml'  # Exclude .yml files from triggering the workflow

# Add permissions block to allow writing to pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd $GITHUB_ACTION_PATH
          npm install parse-diff minimatch glob

      - name: Extract diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > diff.patch
          cat diff.patch

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          FILE_PATTERN: '**/*.{js,jsx,ts,tsx,py,php}'
          MODEL: 'deepseek/deepseek-r1-distill-llama-70b:free'
        run: |
          echo "Starting code review process..."
          node $GITHUB_ACTION_PATH/scripts/code-review/main.js
